# Generated by Django 5.0.6 on 2026-10-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentlogevent',
            index=models.Index(fields=['created_at'], name='agent_agent_created_d3eb08_idx'),
        ),
    ]
