# Generated by Django 5.0.6 on 2026-09-27 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('timeframe', models.CharField(default='1m', max_length=16)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timeframe', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=16)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('final', 'Final')], default='open', max_length=16)),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('title', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('references', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('importance_score', models.PositiveSmallIntegerField(default=1)),
                ('importance_reason', models.CharField(blank=True, default='', max_length=280)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='CardArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('main', 'Main'), ('side', 'Side'), ('aftermath', 'Aftermath')], default='main', max_length=16)),
                ('title', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('references', models.JSONField(blank=True, default=list)),
                ('impacts', models.JSONField(blank=True, default=list)),
                ('time_window', models.CharField(blank=True, default='', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('aftermath_price_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['card_id', 'series_id'],
            },
        ),
        migrations.CreateModel(
            name='AssetCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField(default=0)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='articles.assetseries')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('timeframe', 'period_start'), name='unique_card_per_timeframe'),
        ),
        migrations.AddField(
            model_name='cardarticle',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.card'),
        ),
        migrations.AddField(
            model_name='cardasset',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='articles.card'),
        ),
        migrations.AddField(
            model_name='cardasset',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_assets', to='articles.assetseries'),
        ),
        migrations.AddConstraint(
            model_name='assetcandle',
            constraint=models.UniqueConstraint(fields=('series', 'timestamp'), name='unique_candle_per_series_minute'),
        ),
        migrations.AddConstraint(
            model_name='cardasset',
            constraint=models.UniqueConstraint(fields=('card', 'series'), name='unique_card_asset'),
        ),
    ]
